# Generated by Django 4.2 on 2024-01-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0003_alter_account_driver_alter_account_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='details',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
