# Generated by Django 4.2 on 2024-01-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0004_drive_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
