# Generated by Django 4.2 on 2024-01-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0005_drive_type_notification_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='driver',
            field=models.BooleanField(default=False),
        ),
    ]
