# Generated by Django 4.2 on 2024-01-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0006_application_accepted_alter_account_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='status',
            field=models.CharField(default='Active', max_length=128),
        ),
    ]
