# Generated by Django 4.2 on 2024-01-31 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0007_drive_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drive',
            old_name='pub_date',
            new_name='date',
        ),
    ]
