# Generated by Django 4.2 on 2024-01-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0008_rename_pub_date_drive_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='seats',
            field=models.IntegerField(default=1),
        ),
    ]
